### ISSUE TITLE
Checksum mismatch for temurin-17.0.13+11

### ISSUE THREAD

**Issue by tmr111116** [joschi/java-metadata#53] opened 2024-10-30 12:26 UTC
I encountered a checksum warning when trying to install temurin-17.0.13+11 using `asdf`.

```
$ asdf install java temurin-17.0.13+11
################################################################################################################################################################################################################################### 100.0%
OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz
OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz: FAILED
shasum: WARNING: 1 computed checksum did NOT match
```

The file `OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz.sha256.txt` on the release page (https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.13%2B11) shows:

```
d8b2f77f755d06e81a540834c5be22ed86f3c8a51a20396606c074303f8f9e2d  OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz
```

This checksum does not match the one in this repository:

https://github.com/joschi/java-metadata/blob/677b46b811d9a4030c7200c658217320ccd9679a/docs/checksums/temurin/OpenJDK17U-jdk_aarch64_mac_hotspot_17.0.13_11.tar.gz.sha256#L1

The file timestamp on the release page appears newer, so it may have been re-uploaded.

**Comment by joschi** [comment] 2024-10-30 12:53
> The file timestamp on the release page appears newer, so it may have been re-uploaded.

That might be the reason. Once we recorded a particular artifact, we're skipping it in subsequent runs.

The checksums are there to detect tampering with the artifacts after all. So this confirmed it's working. 😉

**Comment by joschi** [comment] 2024-10-30 13:25
Fixed via https://github.com/joschi/java-metadata/commit/e9b1d1b1edf026206a67e293b0526ca037e6ebfc.

**Closed by joschi** 2024-10-30 13:25 UTC

**Comment by tmr111116** [comment] 2024-10-31 11:27
Thank you for addressing this issue. I was able to install it without any warnings this time. Your prompt response is greatly appreciated!
